### ISSUE TITLE
Proxy exception

### ISSUE THREAD

**Issue by iheos** [usnistgov/asbestos#87]
java.lang.NullPointerException
	at java.util.Objects.requireNonNull(Objects.java:203)
	at gov.nist.asbestos.client.resolver.Ref.rebase(Ref.java:227)
	at gov.nist.asbestos.asbestosProxy.channels.passthrough.PassthroughChannel.transformResponseBody(PassthroughChannel.java:121)
	at gov.nist.asbestos.asbestosProxy.channels.passthrough.PassthroughChannel.transformResponse(PassthroughChannel.java:90)
	at gov.nist.asbestos.asbestosProxy.servlet.ProxyServlet.transformResponse(ProxyServlet.java:757)
	at gov.nist.asbestos.asbestosProxy.servlet.ProxyServlet.doPost(ProxyServlet.java:233)

Possibly a mis-addressed contained resource.

**Comment by iheos** [comment]
Fixed
